SET TIME ZONE 'Asia/Jakarta';

CREATE TABLE "event_instances" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "code" varchar(15) UNIQUE NOT NULL,
    "event_code" varchar(7) NOT NULL,
    "title" varchar(255) NOT NULL,
    "description" TEXT,
    "validate_parent_identifier" BOOL DEFAULT FALSE,
    "parent_identifier_input" TEXT[],
    "validate_child_identifier" BOOL DEFAULT FALSE,
    "child_identifier_input" TEXT[],
    "enforce_community_id" BOOL DEFAULT FALSE,
    "enforce_self_registration" BOOL DEFAULT FALSE,
    "enforce_uniqueness" BOOL DEFAULT FALSE,
    "methods" TEXT[],
    "flow" varchar(10) NOT NULL,
    "start_at" TIMESTAMPTZ NOT NULL,
    "end_at" TIMESTAMPTZ NOT NULL,
    "register_start_at" TIMESTAMPTZ NOT NULL,
    "register_end_at" TIMESTAMPTZ NOT NULL,
    "verify_start_at" TIMESTAMPTZ NOT NULL,
    "verify_end_at" TIMESTAMPTZ NOT NULL,
    "timezone" varchar(50) NOT NULL,
    "location_type" varchar(10) NOT NULL,
    "location_offline_venue" varchar(255),
    "location_online_link" varchar(255),
    "location_detail" TEXT,
    "location_visibility" varchar(255),
    "quota_per_user" INT NOT NULL,
    "capacity" INT NOT NULL,
    "post_details" JSONB DEFAULT '{}',
    "status" varchar(8) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
    "deleted_at" TIMESTAMP
);