version: "3"

services:
  postgres:
    container_name: community
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<<password>>
      - POSTGRES_DB=community_db
    ports:
      - "5432:5432"
