// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/campuses": {
            "get": {
                "description": "Get All Roles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "Get All Roles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mandatory header to access endpoint",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response indicates that the request succeeded and the resources has been fetched and transmitted in the message body",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.List"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.RoleResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation error. This can happen if there is an error validation while create account",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.ErrorValidationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/validator.ErrorValidateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/departments": {
            "get": {
                "description": "Get Departments from Config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get Departments from Config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mandatory header to access endpoint",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response indicates that the request succeeded and the resources has been fetched and transmitted in the message body",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.List"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.DepartmentsResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation error. This can happen if there is an error validation while create account",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.ErrorValidationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/validator.ErrorValidateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/tokens": {
            "get": {
                "description": "Generate both Access and Refresh Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Generate Tokens",
                "parameters": [
                    {
                        "type": "string",
                        "description": "object that needs to be added",
                        "name": "Cookie",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mandatory header to access endpoint",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response indicates that the request succeeded and the resources has been fetched and transmitted in the message body",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.List"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.TokensResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation error. This can happen if there is an error validation while create account",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.ErrorValidationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/validator.ErrorValidateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/users/check/{identifier}": {
            "get": {
                "description": "To check whether user is exist or not by email or phone number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Check User Exist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "object that needs to be added",
                        "name": "identifier",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mandatory header to access endpoint",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response indicates that the request succeeded and the resources has been fetched and transmitted in the message body",
                        "schema": {
                            "$ref": "#/definitions/models.CheckUserExistResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation error. This can happen if there is an error validation while create account",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.ErrorValidationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/validator.ErrorValidateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/users/login": {
            "post": {
                "description": "Login for all type of users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Login User",
                "parameters": [
                    {
                        "description": "User object that needs to be added",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginUserRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "mandatory header to access endpoint",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response indicates that the request succeeded and the resources has been fetched and transmitted in the message body",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.LoginUserResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "tokens": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.TokensResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation error. This can happen if there is an error validation while create account",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.ErrorValidationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/validator.ErrorValidateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/users/logout": {
            "put": {
                "description": "Logout user for all kinds of user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Logout User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mandatory header to access endpoint",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation error. This can happen if there is an error validation while create account",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.ErrorValidationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/validator.ErrorValidateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/users/types": {
            "get": {
                "description": "User Type is something like volunteer, lead or etc.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get All User Types",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mandatory header to access endpoint",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response indicates that the request succeeded and the resources has been fetched and transmitted in the message body",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.List"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.UserTypeResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation error. This can happen if there is an error validation while create account",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.ErrorValidationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/validator.ErrorValidateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "User Type is something like volunteer, lead or etc.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create User Type",
                "parameters": [
                    {
                        "description": "User object that needs to be added",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserTypeRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "mandatory header to access endpoint",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Response indicates that the request succeeded and the resources has been fetched and transmitted in the message body",
                        "schema": {
                            "$ref": "#/definitions/models.UserTypeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation error. This can happen if there is an error validation while create account",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.ErrorValidationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/validator.ErrorValidateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/users/volunteer": {
            "post": {
                "description": "Create user for volunteer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create Volunteer User",
                "parameters": [
                    {
                        "description": "User object that needs to be added",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateVolunteerRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "mandatory header to access endpoint",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Response indicates that the request succeeded and the resources has been fetched and transmitted in the message body",
                        "schema": {
                            "$ref": "#/definitions/models.CreateVolunteerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation error. This can happen if there is an error validation while create account",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.ErrorValidationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/validator.ErrorValidateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/users/{communityId}": {
            "get": {
                "description": "Get all information needed about user by community Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get User By Community ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "object that needs to be added",
                        "name": "communityId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mandatory header to access endpoint",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response indicates that the request succeeded and the resources has been fetched and transmitted in the message body",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.GetOneByCommunityIdResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "roles": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.RoleResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation error. This can happen if there is an error validation while create account",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.ErrorValidationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/validator.ErrorValidateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/users/{identifier}/password": {
            "patch": {
                "description": "Update user Password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update User Password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "object that needs to be added",
                        "name": "identifier",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User object that needs to be added",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserPasswordRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "mandatory header to access endpoint",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Response indicates that the request succeeded and the resources has been fetched and transmitted in the message body",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserPasswordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation error. This can happen if there is an error validation while create account",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.ErrorValidationResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/validator.ErrorValidateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CampusesResponse": {
            "type": "object",
            "properties": {
                "campusCode": {
                    "type": "string"
                },
                "campusName": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.CheckUserExistResponse": {
            "type": "object",
            "properties": {
                "identifier": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "example": "user"
                },
                "user": {
                    "type": "boolean"
                }
            }
        },
        "models.CreateRoleRequest": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "View specifically for event"
                },
                "role": {
                    "type": "string",
                    "example": "event-view-volunteer"
                }
            }
        },
        "models.CreateUserTypeRequest": {
            "type": "object",
            "required": [
                "name",
                "roles",
                "userType"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "General Volunteer"
                },
                "name": {
                    "type": "string",
                    "example": "Volunteer"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "event-view-volunteer",
                        " event-edit-volunteer"
                    ]
                },
                "userType": {
                    "type": "string",
                    "example": "volunteer"
                }
            }
        },
        "models.CreateVolunteerRequest": {
            "type": "object",
            "required": [
                "coolId",
                "dateOfBirth",
                "department_code",
                "isBaptized",
                "isKom100",
                "name",
                "password",
                "placeOfBirth"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "campusCode": {
                    "type": "string",
                    "maxLength": 3,
                    "minLength": 3,
                    "example": "001"
                },
                "coolId": {
                    "type": "integer",
                    "example": 1
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "department_code": {
                    "type": "string",
                    "example": "MUSIC"
                },
                "email": {
                    "type": "string",
                    "example": "jeremy@gmail.com"
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "male",
                        "female"
                    ]
                },
                "isBaptized": {
                    "type": "boolean"
                },
                "isKom100": {
                    "type": "boolean"
                },
                "jemaatId": {
                    "type": "string"
                },
                "kkjNumber": {
                    "type": "string"
                },
                "maritalStatus": {
                    "type": "string",
                    "enum": [
                        "single",
                        "married",
                        "others"
                    ],
                    "example": "active"
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1,
                    "example": "Professionals"
                },
                "password": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 6,
                    "example": "Professionals"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "placeOfBirth": {
                    "type": "string"
                }
            }
        },
        "models.CreateVolunteerResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "campusCode": {
                    "type": "string"
                },
                "communityId": {
                    "type": "string"
                },
                "coolId": {
                    "type": "integer",
                    "example": 1
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "departmentCode": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "isBaptized": {
                    "type": "boolean"
                },
                "isKom100": {
                    "type": "boolean"
                },
                "jemaatId": {
                    "type": "string"
                },
                "kkjNumber": {
                    "type": "string"
                },
                "maritalStatus": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "Profesionals"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "placeOfBirth": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "type": {
                    "type": "string",
                    "example": "coolCategory"
                }
            }
        },
        "models.DepartmentsResponse": {
            "type": "object",
            "properties": {
                "departmentCode": {
                    "type": "string"
                },
                "departmentName": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 401
                },
                "message": {
                    "type": "string",
                    "example": "missing field"
                },
                "status": {
                    "type": "string",
                    "example": "MISSING_FIELD"
                }
            }
        },
        "models.ErrorValidationResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "errors": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "models.GetOneByCommunityIdResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "campusCode": {
                    "type": "string"
                },
                "campusName": {
                    "type": "string"
                },
                "communityId": {
                    "type": "string"
                },
                "coolId": {
                    "type": "integer",
                    "example": 1
                },
                "coolName": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "departmentCode": {
                    "type": "string"
                },
                "departmentName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "isBaptized": {
                    "type": "boolean"
                },
                "isKom100": {
                    "type": "boolean"
                },
                "jemaatId": {
                    "type": "string"
                },
                "kkjNumber": {
                    "type": "string"
                },
                "maritalStatus": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "Profesionals"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "placeOfBirth": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.RoleResponse"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "type": {
                    "type": "string",
                    "example": "coolCategory"
                },
                "userType": {
                    "type": "string"
                }
            }
        },
        "models.List": {
            "type": "object",
            "properties": {
                "data": {},
                "totalRows": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.LoginUserRequest": {
            "type": "object",
            "required": [
                "identifier",
                "password"
            ],
            "properties": {
                "identifier": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.LoginUserResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "campusCode": {
                    "type": "string"
                },
                "communityId": {
                    "type": "string"
                },
                "coolId": {
                    "type": "integer",
                    "example": 1
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "departmentCode": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "isBaptized": {
                    "type": "boolean"
                },
                "isKom100": {
                    "type": "boolean"
                },
                "jemaatId": {
                    "type": "string"
                },
                "kkjNumber": {
                    "type": "string"
                },
                "maritalStatus": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "Profesionals"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "placeOfBirth": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "tokens": {
                    "type": "array",
                    "items": {}
                },
                "type": {
                    "type": "string",
                    "example": "coolCategory"
                },
                "userType": {
                    "type": "string"
                }
            }
        },
        "models.RoleResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "View specifically for event"
                },
                "role": {
                    "type": "string",
                    "example": "event-view-volunteer"
                },
                "type": {
                    "type": "string",
                    "example": "role"
                }
            }
        },
        "models.TokensResponse": {
            "type": "object",
            "properties": {
                "expiresAt": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "example": "accessToken"
                }
            }
        },
        "models.UpdateUserPasswordRequest": {
            "type": "object",
            "required": [
                "confirmPassword",
                "password"
            ],
            "properties": {
                "confirmPassword": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 6
                },
                "password": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 6
                }
            }
        },
        "models.UpdateUserPasswordResponse": {
            "type": "object",
            "properties": {
                "campusCode": {
                    "type": "string"
                },
                "communityId": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "Profesionals"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "type": {
                    "type": "string",
                    "example": "coolCategory"
                },
                "userType": {
                    "type": "string"
                }
            }
        },
        "models.UserTypeResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Volunteer"
                },
                "name": {
                    "type": "string",
                    "example": "Volunteer"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "event-view-event-viewer"
                    ]
                },
                "type": {
                    "type": "string",
                    "example": "userType"
                },
                "userType": {
                    "type": "string",
                    "example": "volunteer"
                }
            }
        },
        "validator.ErrorValidateResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "accountNumber_required"
                },
                "field": {
                    "type": "string",
                    "example": "MISSING_FIELD"
                },
                "message": {
                    "type": "string",
                    "example": "field is missing"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
